# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    
    echo Installing Vault.
    wget --quiet https://releases.hashicorp.com/vault/1.3.1/vault_1.3.1_linux_amd64.zip
    unzip vault_1.3.1_linux_amd64.zip
    sudo mv vault /usr/local/bin
    echo -n Vault version:
    vault version

    vault login $(VAULT_TOKEN)
        
    echo Secret Data from Vault:
    vault kv get -format=json pipelines/secret

    SSN=$(vault kv get -format=json pipelines/secret | jq -r .data.data.ssn)
    USER=$(vault kv get -format=json pipelines/secret | jq -r .data.data.user)

    echo "User: $USER"
    echo "SSN:  $SSN"

  displayName: 'Install Vault'
